### PR TITLE
Add missing feature on tokio

### LINKED ISSUE #7: tokio feature "macros" needed as a primary dependency not as dev-dependency
See example here of a failure caused by this:
https://github.com/Carter12s/roslibrust/actions/runs/3372031636/jobs/5594983367

### PR DESCRIPTION
**Pull request by Carter12s**
Closes #7

### CODE REVIEW

**Comment by bikeshedder** [comment]
I feel like this doesn't need to be a backwards incompatible change as it doesn't compile without this feature anyways. I'd rather make this a `0.2.4` release, no?

**Comment by Carter12s** [comment]
Totally a fair question, and something I debated on and realized I don't understand crates well enough.

My thought process was:

1. My crate depends on deadqueue and on tokio
2. deadqueue updates its tokio features
3. Can my crate now see tokio functions it couldn't previously see which could break my crate?

Trying to google this I did not get a good answer as to whether or not this is actually possible... I don't believe it is. So 0.3.0 might have been overkill.

Your the owner here, and I'm uncertain so going to go ahead and drop the change down to a patch, but if you know how to answer my confusion above I'd love some help.

**Comment by bikeshedder** [comment]
I just released [`deadqueue 0.2.4`](https://crates.io/crates/deadqueue/0.2.4) to crates.io.

Thanks for the fix. :+1:

**Comment by Carter12s** [comment]
https://dev.to/rimutaka/cargo-features-explained-with-examples-194g

I actually did find an answer to my question:
image

and I do think this was technically a 0.3.0 worthy change for future reference.

**Comment by bikeshedder** [comment]
Since the `deadqueue` crate doesn't compile without the `macros` feature it's fixing potential compile issues in the future.

e.g. Let's imagine some project using `deadqueue` and a library in version `1.0` which depends on `tokio` with the `macros` feature enabled. If that library gets an update and no longer needs the `macros` feature it's fine to call it a `1.1` release. The project using that library however will now be unable to compile `deadqueue` as `tokio` is build without the `macros` feature.

For that reason it's actually important to make it a minor version release to unbreak potential future builds.

**Comment by bikeshedder** [comment]
And regarding features. Enabling and disabling features of dependencies should not be considered a backwards incompatible change. The crate depending on it should never assume features implicitly enabled. Features are additive and therefore a project needing the `macros` feature of `tokio` should enable that feature itself and not rely on a dependency enabling that feature.

**Comment by Carter12s** [comment]
Thank you for taking the time to write all this out. I learned a lot from this exchange! Appreciate you taking the time and appreciate your crate in general! :heart:

**Pull request merged**
